### ISSUE TITLE
needhelp: Can’t get Gantt chart to work

### ISSUE THREAD

**Issue by VivianH61** [prosysscience/JSSEnv#1]
When I run the main.py program in the JSS project, the Gantt chart is never displayed on the screen, while the results in wandb indicate that the program is running well. I am quite confused why this happens. Could you please give me some suggestions? Thanks in advance! :)

**Comment by ingambe** [comment]
Are you using a jupyter notebook?

The Gantt chart is produced using Plotly, and I know there are some extra step to do to support it inside Jupyter: https://plotly.com/python/getting-started/

Otherwise, if you run it locally, a webpage should open with the Gantt.

**Comment by VivianH61** [comment]
I'm not using a jupyter notebook. Do you mean that I need to open "https://plotly.com/python/gantt/" this webpage while running it locally?

**Comment by ingambe** [comment]
No, you don't need to. I just know that jupyter can cause trouble sometimes. Outside everything should work without extra steps.

Can you try to run the unit test for the rendering: https://github.com/prosysscience/JSSEnv/blob/c76a5b4bdf32a8662c6ad18787b849c42855db13/tests/test_rendering.py#L6

See if you have any errors in the output and if the gif (named "ta01.gif") is well written in the directory.

**Comment by VivianH61** [comment]
There are no errors but no gif generated. :( Confusing...

**Comment by VivianH61** [comment]
The ta01.gif is well written after the unittest is run. However, after running "main.py", gif is written in the directory. I got those warnings when running "main.py", 
Instructions for updating:
"(pid=45570) non-resource variables are not supported in the long term
(pid=45572) WARNING:tensorflow:From /Users/vv61/anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version"

Are they the reason why gantt chart is not written? Thanks in advance.
![image](https://user-images.githubusercontent.com/41035555/111581294-ef81dc80-87f3-11eb-8957-8b66f8b1e68f.png)

**Comment by ingambe** [comment]
The warnings are "normal", they are linked to Ray
Have you tried to run the setup.py installer?
`python setup.py install`
