### ISSUE TITLE
Error about self.next_time_step

### ISSUE THREAD

**Issue by LaNaGr** [prosysscience/JSSEnv#19]
JSSenv.py, line 367, in increase_time_step
    next_time_step_to_pick = self.next_time_step.pop(0)
IndexError: pop from empty list

Most of conditions that won't happen. Sometimes this error will happen but I haven't find any logic error. The above result is from ta01 dataset. Could you help me please?

**Comment by ingambe** [comment]
Hi,

Did you use the action mask to prevent illegal actions?

Can you provide a minimal code to reproduce your issue?

**Comment by LaNaGr** [comment]
I directly import the environment. First I put ".JSSEnv-master\JSSEnv\envs\jss_env.py" and ta01 next to my file, then I import the class "JssEnv", which can be realized by these code:

from jss_env.py import JssEnv
env = JssEnv(env_config={'instance_path': 'ta01'})

I try to watch some results by:

    for episode in range(10):
        episode_reward = 0
        done = False
        obs = env.reset()
        while not done:
            action = env.action_space.sample()
            obs, reward, done, _ = env.step(action)
            if done:
                print('done!')
            episode_reward += reward
        print(f'episode: {episode + 1}, reward: {episode_reward}')

**Comment by LaNaGr** [comment]
I'm trying to check the action mask now, thank you very much!

**Comment by LaNaGr** [comment]
By the way, I met another error in the environment "jss_env.py" when I use dataset dmu16:
line 315, in step
    time_needed = self.instance_matrix[action][current_time_step_job][1]
IndexError: index 20 is out of bounds for axis 0 with size 20

I'm not sure if my initialization is wrong. Thanks for your help. Waiting for your reply.

**Comment by LaNaGr** [comment]
I've checked the answer in "https://github.com/prosysscience/JSSEnv/issues/9". Sorry that I haven't discovered it yet. Thank you very much! 
And there is still one question that how to find the "legal_action" which is used in "np.random.choice(len(legal_action), 1, p=(legal_action / legal_action.sum()))[0]". Should I use "env.legal_actions"?

Then is that possible to use the mask in  "action = env.action_space.sample(mask=...)"?

**Comment by ingambe** [comment]
> Then is that possible to use the mask in "action = env.action_space.sample(mask=...)"?

No, you will have to sample using the mask:
```python
np.random.choice(len(self.observation_space['action_mask']), 1, p=(self.observation_space['action_mask'] / self.observation_space['action_mask']()))[0]
```
