### ISSUE TITLE
A question about the reward design

### ISSUE THREAD

**Issue by zcaicaros** [prosysscience/JSSEnv#2]
First of all, congratulations! This is an interesting work for DRL solving JSSP.

I have read through the paper and been quite enjoying it. I have a question regarding the reward design. So, if you could elaborate a bit, I will be much appreciated. Thanks in advance.

According to the paper, the reward is designed as:

![image](https://user-images.githubusercontent.com/29399076/122501703-c9a0e980-d027-11eb-9e91-618f0882559c.png)

My question is following:
I hypothesize that the term of processing time makes no difference?
Since no matter what decision is made by the agent, the total cumulated rewards will always have the same amount of processing time of all operations, i.e., it is permutation-invariant. For example, `p11 + p12 + p13 + ... = p13 + p12 + p11 + ... = p12 + p13 + p11 + ...`. Therefore it makes no difference to the agent, and the agent will get the same amount of this reward anyway. However, the total idle time makes a lot of sense to me. So I just wondering have you ever tested that the reward is purely based on the total idle time, that is we just remove the term of processing time in the reward?

I understand that including the processing time will make the reward even denser than purely using the total idle time.

**Comment by ingambe** [comment]
Thank you!

That's a very good observation. You are right. Over an episode, the sum of the processing time is a constant.
We haven't tried to remove it. Depending on your settings, it may or may not have an impact. For full episode rollout with gamma=1, it shouldn't have any impact, but for other settings, it could, and it might be positive.

Please keep up updated about your findings :)

**Comment by zcaicaros** [comment]
> Thank you!
> 
> That's a very good observation. You are right. Over an episode, the sum of the processing time is a constant.
> We haven't tried to remove it. Depending on your settings, it may or may not have an impact. For full episode rollout with gamma=1, it shouldn't have any impact, but for other settings, it could, and it might be positive.
> 
> Please keep up updated about your findings :)

Very clear explanation, thank you!
