### ISSUE TITLE
needhelp: Makespan and Training reward

### ISSUE THREAD

**Issue by guokai-hh** [prosysscience/JSSEnv#3]
How can I get Makespan curve in training process and Training reward in training process?

**Comment by guokai-hh** [comment]
Thank you for your excellent work. I really want to know how to draw the makespan diagram and the reward diagram

**Comment by ingambe** [comment]
The makespan is accessible through the `current_time_step` variable
For plotting, it will depend on your training settings. In our paper we used RLLib, you can have a look at our code to take some inspiration:  https://github.com/prosysscience/JSS

**Comment by guokai-hh** [comment]
> The makespan is accessible through the `current_time_step` variable
> For plotting, it will depend on your training settings. In our paper we used RLLib, you can have a look at our code to take some inspiration: https://github.com/prosysscience/JSS

I ran your program, but there is no output graph in wandb?

**Comment by guokai-hh** [comment]
I am really interested in your work but it is too difficult for me QAQ
