### ISSUE TITLE
A question about learning rate.

### ISSUE THREAD

**Issue by DS-cmd** [prosysscience/JSSEnv#4]
In your paper "A Reinforcement Learning Environment For Job-Shop Scheduling", I saw that you used a linear scheduler for the learning rate and the entropy coefficient who decay linearly each parameter from 0.0006861 to 0.00007783 and from 0.0002458 to 0.002042 respectively. 
I am confused about the learning rate and the entropy coefficient. Is this learning rate Actor-Net's learning rate? Is this entropy coefficient Critric-Net's learning rate?

**Comment by ingambe** [comment]
The actor and the critic share the same learning rate.
The entropy coefficient is a term that is used to encourage exploration. I recommend you to read this paper that explore the impact of entropy on policy optimization: https://arxiv.org/abs/1811.11214

**Comment by DS-cmd** [comment]
Thanks for your suggestion.
