### ISSUE TITLE
About your code

### ISSUE THREAD

**Issue by sgfuigh** [prosysscience/JSSEnv#5]
Hello,after studying your code, I would like to ask how to get the state representation and action distribution updates of each time step from your encapsulated environment. I can't print the expression of the intermediate state of each step.

**Comment by ingambe** [comment]
Hello,
The environment after each call to the `step` function return the state, reward, a boolean to indicate if the environment is done, and an empty dictionary (to follow OpenAi's convention)
The state itself is a dictionary with two entries:
- `action_mask`: Contain a boolean vector with legal actions
- `real_obs`: The observation, containing for each job, the attributes you can use to make predictions

**Comment by sgfuigh** [comment]
Yes, thank you so much!
And I wonder how to get specific results for each step? How can I directly see the &nbsp;return results of the environment ?



发自我的iPad


------------------ Original ------------------
From: Pierre TASSEL ***@***.***&gt;
Date: Wed,Jan 5,2022 6:57 PM
To: prosysscience/JSSEnv ***@***.***&gt;
Cc: sgfuigh ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prosysscience/JSSEnv] About your code (Issue #5)





 
Hello,
 The environment after each call to the step function return the state, reward, a boolean to indicate if the environment is done, and an empty dictionary (to follow OpenAi's convention)
 The state itself is a dictionary with two entries:
  
action_mask: Contain a boolean vector with legal actions 

real_obs: The observation, containing for each job, the attributes you can use to make predictions 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
